# using VSCode extesion REST Client
GET http://localhost:4001/api
###
POST http://localhost:4001/api/auth/register
Content-Type: application/json

{
  "username": "abc",
  "password": "Abc123!"
}
###
POST http://localhost:4001/api/auth/login
Content-Type: application/json

{
  "username": "leo100",
  "password": "Abc123!"
}
###
GET http://localhost:4001/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlYTQ5ODU2ZDExMjhlM2Q5YjYwOWNhZiIsInVzZXJuYW1lIjoibGVvMTAwIiwiaWF0IjoxNTg3ODYyNDIxfQ.-3sKKwbuQyh40uqOYg41K4oNDePhwvHGCqhr5ZqudKQ